repos:
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.8
    hooks:
    -   id: flake8
        args: ['--max-line-length=90']
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
